sonar.organization=francescoigensia
sonar.projectKey=Francescoigensia_webapp

# On cible uniquement les bons fichiers pour éviter de scanner les dossiers générés
sonar.sources=app.js
sonar.tests=app.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
